# Generated by Django 3.2.13 on 2023-06-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='name',
            field=models.CharField(help_text='Ingrese el nombre del digimon', max_length=128, unique=True),
        ),
    ]
